[project]
name = "lab6"
version = "0.1.0"
description = "Lyft Motion Prediction (l5kit)"
readme = "README.md"
requires-python = ">=3.8,<3.9"
dependencies = [
    "l5kit==1.5.0",
    "imageio>=2.9.0",
    "protobuf>=3.12.2,<4",
    "kaggle>=1.7.4.5",
    "jupyter>=1.1.1",
    "ipykernel>=6.29.5",
    "bokeh<3",
]

[tool.uv]
constraint-dependencies = ["pywinpty<2.0.14"]
