[project]
name = "study-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13, <3.14"
dependencies = [
  "ipykernel>=7.2.0",
  "joblib>=1.5.3",
  "kaggle>=2.1.2",
  "kagglehub>=1.0.2",
  "matplotlib>=3.10.9",
  "numpy>=2.4.6",
  "pandas>=3.0.3",
  "pyarrow>=24.0.0",
  "python-dotenv>=1.2.2",
  "seaborn>=0.13.2",
]

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.basedpyright]
venvPath = "."
venv = ".venv"

typeCheckingMode = "basic"
reportAny = false

analysis.diagnosticMode = "openFilesOnly"
analysis.autoSearchPaths = true
analysis.useLibraryCodeForTypes = true

exclude = ["**/.venv", "**/__pycache__"]

reportMissingTypeStubs = "none"

[dependency-groups]
lab2 = [
    "scikit-learn>=1.9.1",
]
lab3 = [
    "albumentationsx[headless]>=2.4.13",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
    "zarr>=3.4.0",
]
lab4 = [
    "nltk>=3.10.3",
    "scikit-learn>=1.9.1",
    "spacy>=3.8.16",
]
lab5 = [
    "imbalanced-learn>=0.14.2",
    "lightgbm>=4.7.0",
    "scikit-learn>=1.9.1",
    "shap>=0.52.0",
    "xgboost>=3.4.1",
]
